on:
  workflow_call:
    inputs:
      message:
        description: message
        required: true
        type: string

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - run: echo Setup

  Build1:
    runs-on: ubuntu-latest
    needs: Setup
    steps:
    - run: echo ${{ inputs.message }}