on:
  workflow_dispatch:
    inputs:
      serviceA_deploy:
        description: serviceAリリース
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false

      serviceB_deploy:
        description: serviceBリリース
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false

      serviceC_deploy:
        description: serviceCリリース
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false

      release_version:
        description: リリースバージョンの明示的な指定(optional)  入力した場合はmajor_releaseオプションは無視される。
        type: string
        required: true

name: Deployment Test

jobs:
  serviceA-deploy:
    if: ${{ inputs.serviceA_deploy == 'true' }}
    uses: ./.github/workflows/deployment.yml
    with:
      message: serviceA

  serviceB-deploy:
    if: ${{ inputs.serviceB_deploy == 'true' }}
    uses: ./.github/workflows/deployment.yml
    with:
      message: serviceB
  
  serviceC-deploy:
    if: ${{ inputs.serviceC_deploy == 'true' }}
    uses: ./.github/workflows/deployment.yml
    with:
      message: serviceC